### ISSUE TITLE
Django Dockerfile for CentOS 7 fails to build

### ISSUE THREAD

**Issue by web-snake** [CentOS/CentOS-Dockerfiles#20]
Following the instructions from : https://github.com/CentOS/CentOS-Dockerfiles/tree/master/Django/centos7
to build the Django Dockerfile
I'm getting the following error: 
Invalid namespace name (), only [a-z0-9_] are allowed, size between 4 and 30
I'm new to Docker and just trying to get a working example going so its possible that I'm doing something very stupid. But the instructions are so simple I'm not sure what I could have messed up.
I don't know what namespace the error refers to.
I'm using Docker version 1.3.2, build 39fa2fa/1.3.2
I just installed CentOS7 with the Gnome desktop.

**Comment by jperrin** [comment]
There is a docker bug that doesn't allow you to create tagged names. instead of following the documentation exactly for `docker build -rm -t /django:centos7` try something like `docker build -rm -t django/centos7`

**Comment by web-snake** [comment]
$ docker build -rm -t django/centos7 .
worked. Thanx.
