### ISSUE TITLE
Missing path to "/bin" in $PATH for CentOS 6 docker image.

### ISSUE THREAD

**Issue by michalsarna** [CentOS/CentOS-Dockerfiles#21]
As in topic. 
I'm using CentOS 6 for my base and from some time (2-3 weeks) i've noticed that there is no "/bin" in $PATH.

**Comment by jperrin** [comment]
There would be something in how you're building your containers that's altering the $PATH, or an init script that's resetting it for your service. By default, you get

```bash
$ docker run --rm  -ti  centos:6  /bin/bash
[root@ad54d7b8c652 /]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

And the output of `strings /bin/bash` from inside the container shows `/usr/local/bin:/bin:/usr/bin` (it's the basic path compiled into bash by default)

**Comment by jperrin** [comment]
If you point me to what you're doing, I can help you figure out what's going on.

**Comment by michalsarna** [comment]
Hi.

I've figured it out. On my systems when I'm logging as root it's not working, no "/bin" in $PATH. 
If I'm using any other user account and go sudo to root it's working. 
Sorry for disturbance. 

All best.
