### ISSUE TITLE
Cannot pull postgresql docker image

### ISSUE THREAD

**Issue by henros0** [CentOS/CentOS-Dockerfiles#221]
I wanted to pull a postgresql image that runs on CentOS, and I got to: [dockerhub-centos/postgresql](https://hub.docker.com/r/centos/postgresql).

I used the pull command: `docker pull centos/postgresql`

I recieved: `Error response from daemon: manifest for centos/postgresql:latest not found: manifest unknown: manifest unknown`

**Comment by MeenuyD** [comment]
Hello @henros0 could you please try this `docker pull centos/postgresql-96-centos7`

**Comment by henros0** [comment]
@MeenuyD thank you!
It works!
