### ISSUE TITLE
default root password in various scenarios

### ISSUE THREAD

**Issue by Tim-HU** [CentOS/CentOS-Dockerfiles#25]
This is regarding Docker official Centos6 and Centos7 images

There are 3 separate questions:
(1) When started using "docker RUN centos", what is the root password and how to find it?
(2) When started from a derived image (image derived from offical docker centos via using Dockerfile FROM entry) , what is the root password and how to find it?
(3) In both cases, if the answer is "you need to set root password inside Dockerfile", what is the best recommended method to set it. ("yum install passwd; passwd;" is one option, but is this the best practice? )

Thank you very much!

**Comment by jperrin** [comment]
1. The root password is randomly generated, as default passwords present a security risk.
2. Same as point 1. You're just a few layers deeper. 
3. If you need to authenticate as root, I would argue that you're already outside the scope of 'best practices'. You would need to set the password yourself if you wish to have one. This could be done as you suggest, or by replacing the hashed password in /etc/shadow with a known hash, or via other tools (and dependencies) like ansible. It's entirely up to you and the way that suits your environment best.
