### ISSUE TITLE
MariaDB / mysqld is stopped with SIGKILL

### ISSUE THREAD

**Issue by erikced** [CentOS/CentOS-Dockerfiles#28]
mysqld_safe, which is the main process in the MariaDB image, does not forward SIGTERM to mysqld, forcing docker to kill it and its children (including mysqld) with SIGKILL, i.e. without giving mysqld a chance perform a clean shutdown.
The official Docker MariaDB  image calls mysqld directly instead of mysqld_safe and avoids this issue.

**Comment by jperrin** [comment]
Which are you referring to? https://github.com/dockerfile/mariadb/blob/master/Dockerfile 

this calls mysqld_safe as well.

**Comment by erikced** [comment]
https://github.com/docker-library/mariadb/blob/471e5cbdea21c3b080809ba3376990b12cf4da05/5.5/Dockerfile (referred to from https://registry.hub.docker.com/u/library/mariadb/)
