### ISSUE TITLE
Inconsistency in env variables between upstream postgres image and centos one

### ISSUE THREAD

**Issue by rtnpro** [CentOS/CentOS-Dockerfiles#36]
It seems that ``centos/postgresql-94-centos7`` container uses different but similar environment variables in contrast to upsteam ``postgres`` container. This prohibits using ``centos/postgresql-94-centos7`` in application images depending on official ``postgres`` container image, e.g.. ``sentry``, without customizing them.

We could use the same nomenclature for the environment variables in the centos based and official postgres container images. This will make adopting ``centos/postgresql-94-centos7`` image much more easier.

- Upstream postgres repo: https://hub.docker.com/_/postgres/
- CentOS postgresql repo: https://hub.docker.com/r/centos/postgresql-94-centos7/

**Comment by rtnpro** [comment]
@kbsingh what do you think?

**Comment by jperrin** [comment]
Do you have a patchset we could adopt to be compliant with what is expected?

**Comment by rtnpro** [comment]
@jperrin I will work on a patch for the fix and send a PR :)

**Comment by goern** [comment]
@rtnpro ping

**Comment by rtnpro** [comment]
@goern This got fixed in https://github.com/CentOS/CentOS-Dockerfiles/pull/37. Closing this issue.
