### ISSUE TITLE
Docker registry builds are failing for httpd

### ISSUE THREAD

**Issue by rmelick** [CentOS/CentOS-Dockerfiles#46]
Builds of centos/httpd are failing since at least 2015-12-28.

https://hub.docker.com/r/centos/httpd/builds/

Looking at the most recent failure, it seems there are issues with updating httpd
https://hub.docker.com/r/centos/httpd/builds/bmjn5nzj2xv683uoem6mckr/

```
 Installing : httpd-2.4.6-40.el7.centos.x86_64 6/6[91mError unpacking rpm package httpd-2.4.6-40.el7.centos.x86_64[0m[91m [0m error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file error: httpd-2.4.6-40.el7.centos.x86_64: install failed
```

It seems like this could be related to the issue opened with the docker team: https://github.com/docker/docker/issues/6980

**Comment by guiyomh** [comment]
:+1: same bug

**Comment by jperrin** [comment]
This is a docker hub issue with a change in their back-end. There's nothing we can do about this. Their backend no longer allows the cap_set_file priv for some reason, which httpd needs when doing the install.

**Comment by macropin** [comment]
Our builds are failing too. https://hub.docker.com/r/panubo/php-apache-c7/builds/.

**Comment by justincormack** [comment]
This should be resolved now see https://github.com/docker/hub-feedback/issues/461

**Comment by macropin** [comment]
Please trigger a build of the image.

**Comment by jperrin** [comment]
Done. It appears to have built successfully. Closing this one, finally.
