### ISSUE TITLE
centos/registry:2 image is missing on Docker Hub

### ISSUE THREAD

**Issue by tnozicka** [CentOS/CentOS-Dockerfiles#52]
centos/registry:2 is missing on Docker Hub. 

@jperrin 
You merged PR #47 which stated:
> Please set up an automated build on Docker Hub and publish this probably as "centos/registry:2".

but this image is missing on Docker Hub.

Please set up this automated build.

Thanks.

**Comment by jperrin** [comment]
ack, yeah. got distracted. I'll correct that now.

**Comment by jperrin** [comment]
Closing this one, as it's up on the hub now -> https://hub.docker.com/r/centos/registry/
