### ISSUE TITLE
MariaDB: Import sql files in a specific directory

### ISSUE THREAD

**Issue by nalipaz** [CentOS/CentOS-Dockerfiles#53]
I would like to request that the MariaDB image be setup to allow importing sql files that are placed in a given directory. The latest version of the official mysql docker image currently allows importing data on startup. Details of how they are doing it can be seen here:

https://github.com/docker-library/mysql/blob/5b1a6a2b50efceac44579df0936facfee654a805/5.7/docker-entrypoint.sh#L96

**Comment by jperrin** [comment]
I'm certainly open to considering this if you're willing to patch it.

**Comment by jperrin** [comment]
@dustymabe thoughts/comments?

**Comment by nalipaz** [comment]
I have opened a PR for this feature so I am closing this in favor of the PR.
