### ISSUE TITLE
Update wordpress example and publish to docker hub

### ISSUE THREAD

**Issue by dustymabe** [CentOS/CentOS-Dockerfiles#74]
The wordpress example needs to be updated (should probably not use supervisord, etc). 

Can we get it updated and then start publishing it on docker hub? 

I just realized we weren't using the centos based image in our Atomic App: https://github.com/projectatomic/nulecule-library/blob/master/wordpress-centos7-atomicapp/Nulecule#L23

**Comment by jperrin** [comment]
I'm happy to update it, but I'd defer to you on 'best practice' for the container. If you want to submit a pull request for an updated version, I'm happy to merge it in and auto-build it

**Comment by surajssd** [comment]
So this container has `mariadb` installed in it, so I would suggest to make it wordpress only and expect user to populate some environment variables, similar to canonical wordpress example: https://hub.docker.com/_/wordpress/ 

Let user of this docker image populate database.

cc: @abhi1004 @containscafeine
