### ISSUE TITLE
HTTPD does not need to run as root

### ISSUE THREAD

**Issue by thesteve0** [CentOS/CentOS-Dockerfiles#79]
Hey all:
There is no reason for HTTPD docker image to run as root. I am working on building one that does not need root - so it will also run in OpenShift. Let me know if you want me to do PR on it.
Thanks
Steve

**Comment by jperrin** [comment]
yes please. happy to merge it in when you have it ready.

**Comment by thesteve0** [comment]
Is it ok if we start the container to use 8080 rather than 80? I think this means we would need to copy in a httpd.conf

**Comment by jperrin** [comment]
On the face of it, I don't think this is a good idea. 80's pretty well established as http, and 8080 as tomcat. I don't see other example containers for httpd running on ports other than 80, so there's an expectation that's where we'd have it as well.

**Comment by thesteve0** [comment]
Hey Jperrin:
Here is the repo where I built my non-root, volume using HTTPD image. Do you want to review before I actually think about doing a merge

https://github.com/thesteve0/myDockerImages/tree/master/simpleNRVol

**Comment by jperrin** [comment]
The run section of the readme should reference 8080 instead of 80, since we're changing the exposed port. 

@dustymabe Any comments here?

**Comment by dustymabe** [comment]
I would say open up a PR and we can make comments there.
